from django.urls import path

from . import views

app_name = "recipes"

urlpatterns = [
    path("", views.recipe_list, name="list"),
    path("brassins/", views.brew_list, name="brews"),
    path("brassins/ajouter/", views.brew_create, name="brew_create"),
    path("brassins/<int:pk>/", views.brew_detail, name="brew_detail"),
    path("brassins/<int:pk>/modifier/", views.brew_edit, name="brew_edit"),
    path("brassins/<int:pk>/supprimer/", views.brew_delete, name="brew_delete"),
    path("brassins/<int:pk>/consommer-stock/", views.brew_consume_stock, name="brew_consume_stock"),
    path("brassins/<int:pk>/annuler-consommation-stock/", views.brew_rollback_stock, name="brew_rollback_stock"),
    path("parametres/", views.equipment_settings, name="equipment_settings"),
    path("courses/", views.shopping_list, name="shopping_list"),
    path("courses/ajouter/", views.shopping_item_create, name="shopping_item_create"),
    path("courses/<int:pk>/cocher/", views.shopping_item_toggle, name="shopping_item_toggle"),
    path("courses/<int:pk>/supprimer/", views.shopping_item_delete, name="shopping_item_delete"),
    path("parametres/remise-a-zero/", views.database_reset, name="database_reset"),
    path("parametres/sauvegarde.json", views.backup_download, name="backup_download"),
    path("parametres/restaurer/", views.backup_restore, name="backup_restore"),
    path("categories/", views.category_list, name="categories"),
    path("categories/ajouter/", views.category_create, name="category_create"),
    path("categories/<int:pk>/modifier/", views.category_edit, name="category_edit"),
    path("categories/<int:pk>/supprimer/", views.category_delete, name="category_delete"),
    path("catalogue/", views.catalog_list, name="catalog"),
    path("catalogue/ajouter/", views.catalog_create, name="catalog_create"),
    path("catalogue/<int:pk>/modifier/", views.catalog_edit, name="catalog_edit"),
    path("catalogue/<int:pk>/supprimer/", views.catalog_delete, name="catalog_delete"),
    path("recettes/nouvelle/", views.recipe_create, name="create"),
    path("recettes/importer/", views.recipe_import, name="import"),
    path("recettes/<int:pk>/", views.recipe_detail, name="detail"),
    path("recettes/<int:pk>/historique/", views.recipe_history, name="history"),
    path("recettes/<int:pk>/historique/<int:version_pk>/restaurer/", views.recipe_restore, name="restore"),
    path("recettes/<int:pk>/versions/ajouter/", views.recipe_version_create, name="version_create"),
    path("recettes/<int:pk>/versions/<int:version_pk>/supprimer/", views.recipe_version_delete, name="version_delete"),
    path("recettes/<int:pk>/brassage/", views.mash_list, name="mash"),
    path("recettes/<int:pk>/brassage/ajouter/", views.mash_create, name="mash_create"),
    path("recettes/<int:pk>/exporter/", views.recipe_export, name="export"),
    path("recettes/<int:pk>/ebullition/", views.boil_settings_update, name="boil_settings"),
    path("recettes/<int:pk>/efficacite/", views.recipe_efficiency_update, name="efficiency_update"),
    path("recettes/<int:pk>/nom/", views.recipe_name_update, name="name_update"),
    path("recettes/<int:pk>/categorie/", views.recipe_category_update, name="category_update"),
    path("recettes/<int:pk>/notes/", views.recipe_notes_update, name="notes_update"),
    path("recettes/<int:pk>/scale/", views.recipe_scale, name="scale"),
    path("recettes/<int:pk>/supprimer/", views.recipe_delete, name="delete"),
    path("recettes/<int:pk>/ingredients/ajouter/", views.ingredient_create, name="ingredient_create"),
    path("ingredients/<int:pk>/modifier/", views.ingredient_edit, name="ingredient_edit"),
    path("ingredients/<int:pk>/supprimer/", views.ingredient_delete, name="ingredient_delete"),
    path("paliers/<int:pk>/modifier/", views.mash_edit, name="mash_edit"),
    path("paliers/<int:pk>/supprimer/", views.mash_delete, name="mash_delete"),
    path("fermentation/<int:pk>/modifier/", views.fermentation_edit, name="fermentation_edit"),
    path("fermentation/<int:pk>/supprimer/", views.fermentation_delete, name="fermentation_delete"),
    path("recettes/<int:pk>/fermentation/reordonner/", views.fermentation_reorder, name="fermentation_reorder"),
    path("recettes/<int:pk>/fermentation/ajouter/", views.fermentation_create, name="fermentation_create"),
]
