# Generated by Django 5.2.17 on 2026-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('batch_size_l', models.DecimalField(decimal_places=2, default=20, max_digits=6, verbose_name='volume final (L)')),
                ('efficiency', models.DecimalField(decimal_places=2, default=75, max_digits=5, verbose_name='rendement (%)')),
                ('target_og', models.DecimalField(decimal_places=3, default=1.05, max_digits=5, verbose_name='densité initiale cible')),
                ('target_ibu', models.DecimalField(decimal_places=1, default=25, max_digits=6, verbose_name='IBU cible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
