# Generated by Django 5.2.17 on 2026-10-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('kind', models.CharField(choices=[('malt', 'Malt'), ('hop', 'Houblon'), ('yeast', 'Levure')], max_length=10, verbose_name='type')),
                ('amount_g', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='quantité (g)')),
                ('ppg', models.DecimalField(decimal_places=1, default=37, max_digits=5, verbose_name='potentiel (PPG)')),
                ('alpha_acid', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='acides alpha (%)')),
                ('boil_minutes', models.PositiveIntegerField(default=60, verbose_name='ébullition (min)')),
                ('attenuation', models.DecimalField(decimal_places=2, default=78, max_digits=5, verbose_name='atténuation (%)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
    ]
