# Generated by Django 5.2.17 on 2026-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='addition',
            field=models.CharField(blank=True, max_length=100, verbose_name='ajout'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='color_ebc',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='couleur (EBC)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='coût total'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='form',
            field=models.CharField(blank=True, max_length=60, verbose_name='forme'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120, verbose_name='fabricant / laboratoire'),
        ),
    ]
