# Generated by Django 5.2.17 on 2026-10-02 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredient_addition_ingredient_color_ebc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('kind', models.CharField(choices=[('malt', 'Malt'), ('hop', 'Houblon'), ('yeast', 'Levure')], max_length=10, verbose_name='type')),
                ('manufacturer', models.CharField(blank=True, max_length=120, verbose_name='fabricant / laboratoire')),
                ('form', models.CharField(blank=True, max_length=60, verbose_name='forme')),
                ('color_ebc', models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='couleur (EBC)')),
                ('ppg', models.DecimalField(decimal_places=1, default=37, max_digits=5, verbose_name='potentiel (PPG)')),
                ('alpha_acid', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='acides alpha (%)')),
                ('attenuation', models.DecimalField(decimal_places=2, default=78, max_digits=5, verbose_name='atténuation (%)')),
            ],
            options={
                'verbose_name': 'ingrédient du catalogue',
                'verbose_name_plural': 'ingrédients du catalogue',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_ingredients', to='recipes.ingredientcatalog'),
        ),
    ]
