# Generated by Django 5.2.17 on 2026-10-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredientcatalog_ingredient_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MashStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='ordre')),
                ('name', models.CharField(max_length=120, verbose_name='nom du palier')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='température (°C)')),
                ('duration_min', models.PositiveIntegerField(verbose_name='durée (min)')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mash_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
