# Generated by Django 5.2.17 on 2026-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_mashstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='boil_time_min',
            field=models.PositiveIntegerField(default=60, verbose_name="durée d'ébullition (min)"),
        ),
    ]
