# Generated by Django 5.2.17 on 2026-10-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_boil_time_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
    ]
