# Generated by Django 5.2.17 on 2026-10-02 18:05

from decimal import Decimal

from django.db import migrations, models


def convert_ppg_to_potential_yield(apps, schema_editor):
    for model_name in ("Ingredient", "IngredientCatalog"):
        model = apps.get_model("recipes", model_name)
        for item in model.objects.all():
            item.potential_yield = (Decimal(item.potential_yield) / Decimal("46.214") * 100).quantize(Decimal("0.1"))
            item.save(update_fields=["potential_yield"])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ppg',
            new_name='potential_yield',
        ),
        migrations.RenameField(
            model_name='ingredientcatalog',
            old_name='ppg',
            new_name='potential_yield',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='potential_yield',
            field=models.DecimalField(decimal_places=1, default=80, max_digits=5, verbose_name='rendement potentiel (%)'),
        ),
        migrations.AlterField(
            model_name='ingredientcatalog',
            name='potential_yield',
            field=models.DecimalField(decimal_places=1, default=80, max_digits=5, verbose_name='rendement potentiel (%)'),
        ),
        migrations.RunPython(convert_ppg_to_potential_yield, migrations.RunPython.noop),
    ]
