# Generated by Django 5.2.17 on 2026-10-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_ingredient_ppg_remove_ingredientcatalog_ppg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter_cm', models.DecimalField(decimal_places=1, default=40, max_digits=6, verbose_name='diamètre de la cuve (cm)')),
                ('height_cm', models.DecimalField(decimal_places=1, default=45, max_digits=6, verbose_name='hauteur de la cuve (cm)')),
                ('evaporation_l_min', models.DecimalField(decimal_places=2, default=0.25, max_digits=5, verbose_name='évaporation (L/min)')),
                ('grain_absorption_l_kg', models.DecimalField(decimal_places=2, default=0.8, max_digits=5, verbose_name='absorption des grains (L/kg)')),
                ('dead_space_l', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='volume mort (L)')),
                ('mash_efficiency', models.DecimalField(decimal_places=1, default=75, max_digits=5, verbose_name="rendement d'empâtage (%)")),
            ],
        ),
    ]
