# Generated by Django 5.2.17 on 2026-10-02 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_equipmentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Modification', max_length=120, verbose_name='modification')),
                ('snapshot', models.JSONField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
