# Generated by Django 5.2.17 on 2026-10-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_recipeversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FermentationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='ordre')),
                ('phase', models.CharField(choices=[('Fermentation primaire', 'Fermentation primaire'), ('Fermentation secondaire', 'Fermentation secondaire'), ('Dry hop', 'Dry hop'), ('Cold crash', 'Cold crash'), ('Conditionnement', 'Conditionnement'), ('Autre', 'Autre')], max_length=60, verbose_name='phase')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='température (°C)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='durée (jours)')),
                ('action', models.CharField(blank=True, max_length=200, verbose_name='action / commentaire')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentation_steps', to='recipes.recipe')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
