# Generated by Django 5.2.17 on 2026-10-02 19:38

from django.db import migrations, models


BJCP_CATEGORIES = [
    ("01", "Standard American Beer"),
    ("02", "International Lager"),
    ("03", "Czech Lager"),
    ("04", "Pale Malty European Lager"),
    ("05", "German Wheat Beer"),
    ("06", "Amber Malty European Lager"),
    ("07", "Amber Bitter European Beer"),
    ("08", "Dark European Beer"),
    ("09", "Strong European Beer"),
    ("10", "German Leichtbier"),
    ("11", "British Golden Ale"),
    ("12", "Pale Commonwealth Beer"),
    ("13", "Brown British Beer"),
    ("14", "Scottish Ale"),
    ("15", "Irish Beer"),
    ("16", "Dark British Beer"),
    ("17", "Strong British Ale"),
    ("18", "Pale American Ale"),
    ("19", "Amber and Brown American Beer"),
    ("20", "American Porter and Stout"),
    ("21", "IPA"),
    ("22", "Strong American Ale"),
    ("23", "European Sour Ale"),
    ("24", "Belgian Ale"),
    ("25", "Strong Belgian Ale"),
    ("26", "Trappist Ale"),
    ("27", "Historical Beer"),
    ("28", "American Wild Ale"),
    ("29", "Fruit Beer"),
    ("30", "Spiced Beer"),
    ("31", "Alternative Fermentables Beer"),
    ("32", "Smoked Beer"),
    ("33", "Wood-Aged Beer"),
    ("34", "Specialty Beer"),
]


def seed_categories(apps, schema_editor):
    BeerCategory = apps.get_model("recipes", "BeerCategory")
    BeerCategory.objects.bulk_create(
        [BeerCategory(code=code, name=name) for code, name in BJCP_CATEGORIES]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_fermentationstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code BJCP')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'catégorie de bière',
                'verbose_name_plural': 'catégories de bière',
                'ordering': ['code'],
            },
        ),
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
