# Generated by Django 5.2.17 on 2026-10-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_beercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='beercategory',
            name='abv_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ABV maximum (%)'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='abv_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ABV minimum (%)'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='ebc_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='EBC maximum'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='ebc_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='EBC minimum'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='fg_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='FG maximale'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='fg_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='FG minimale'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='ibu_max',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='IBU maximum'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='ibu_min',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='IBU minimum'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='og_max',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='OG maximale'),
        ),
        migrations.AddField(
            model_name='beercategory',
            name='og_min',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='OG minimale'),
        ),
    ]
