# Generated by Django 5.2.17 on 2026-10-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_beercategory_abv_max_beercategory_abv_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.beercategory', verbose_name='catégorie BJCP'),
        ),
    ]
