# Generated by Django 5.2.17 on 2026-10-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcatalog',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0, verbose_name='quantité disponible'),
        ),
    ]
