# Generated by Django 5.2.17 on 2026-10-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_remove_legacy_beer_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=120, verbose_name='nom de la recette')),
                ('status', models.CharField(choices=[('planned', 'Planifié'), ('brewing', 'Brassage en cours'), ('fermenting', 'Fermentation'), ('conditioning', 'Garde / conditionnement'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='planned', max_length=20, verbose_name='statut')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='date prévue')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('actual_batch_size_l', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume réel (L)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brews', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
    ]
