# Generated by Django 5.2.17 on 2026-10-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_brew'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='actual_fg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DF mesurée'),
        ),
        migrations.AddField(
            model_name='brew',
            name='actual_og',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DI mesurée'),
        ),
        migrations.AddField(
            model_name='brew',
            name='actual_preboil_volume_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume pré-ébullition réel (L)'),
        ),
        migrations.AddField(
            model_name='brew',
            name='fermentation_temperature_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='température de fermentation (°C)'),
        ),
    ]
