# Generated by Django 5.2.17 on 2026-10-02 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_brew_actual_fg_brew_actual_og_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='recipe_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brews', to='recipes.recipeversion'),
        ),
        migrations.AddField(
            model_name='brew',
            name='recipe_version_label',
            field=models.CharField(blank=True, max_length=200, verbose_name='version de recette'),
        ),
    ]
