# Generated by Django 5.2.17 on 2026-10-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_brew_recipe_version_brew_recipe_version_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='stock_consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='stock consommé le'),
        ),
    ]
