# Generated by Django 5.2.17 on 2026-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_brew_stock_consumed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='stock_consumed_items',
            field=models.JSONField(blank=True, default=list, verbose_name='lignes de stock consommées'),
        ),
        migrations.AlterField(
            model_name='ingredientcatalog',
            name='quantity_available',
            field=models.IntegerField(default=0, verbose_name='quantité disponible'),
        ),
    ]
