# Generated by Django 5.2.17 on 2026-10-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_brew_stock_consumed_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='planned_abv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ABV prévu (%)'),
        ),
        migrations.AddField(
            model_name='brew',
            name='planned_batch_size_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='volume prévu (L)'),
        ),
        migrations.AddField(
            model_name='brew',
            name='planned_efficiency',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='rendement prévu (%)'),
        ),
        migrations.AddField(
            model_name='brew',
            name='planned_fg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DF prévue'),
        ),
        migrations.AddField(
            model_name='brew',
            name='planned_og',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='DI prévue'),
        ),
    ]
