# Generated by Django 5.2.17 on 2026-10-03 05:54

import django.db.models.deletion
from django.db import migrations, models


def populate_version_numbers(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    RecipeVersion = apps.get_model("recipes", "RecipeVersion")
    for recipe in Recipe.objects.all():
        versions = list(RecipeVersion.objects.filter(recipe_id=recipe.pk).order_by("created_at", "pk"))
        for number, version in enumerate(versions, start=1):
            RecipeVersion.objects.filter(pk=version.pk).update(version_number=number)
        if versions:
            Recipe.objects.filter(pk=recipe.pk).update(current_version_id=versions[-1].pk)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_brew_planned_abv_brew_planned_batch_size_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.recipeversion', verbose_name='version active'),
        ),
        migrations.AddField(
            model_name='recipeversion',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='numéro de version'),
        ),
        migrations.RunPython(populate_version_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('recipe', 'version_number'), name='unique_recipe_version_number'),
        ),
    ]
