# Generated by Django 5.2.17 on 2026-10-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0024_recipe_current_version_recipeversion_version_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='kind',
            field=models.CharField(choices=[('malt', 'Malt'), ('hop', 'Houblon'), ('yeast', 'Levure'), ('other', 'Divers')], max_length=10, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='ingredientcatalog',
            name='kind',
            field=models.CharField(choices=[('malt', 'Malt'), ('hop', 'Houblon'), ('yeast', 'Levure'), ('other', 'Divers')], max_length=10, verbose_name='type'),
        ),
    ]
