# Generated by Django 5.2.17 on 2026-10-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_ingredient_kind_alter_ingredientcatalog_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='notes'),
        ),
    ]
