# Generated by Django 5.2.17 on 2026-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0026_ingredient_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120, verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='ingredientcatalog',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120, verbose_name='fournisseur'),
        ),
    ]
