# Generated by Django 5.2.17 on 2026-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_alter_ingredient_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='product_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='référence produit'),
        ),
        migrations.AddField(
            model_name='ingredientcatalog',
            name='product_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='référence produit'),
        ),
    ]
