# Generated by Django 5.2.17 on 2026-10-03 07:27

from django.db import migrations, models


def convert_minutes_to_hours(apps, schema_editor):
    EquipmentSettings = apps.get_model("recipes", "EquipmentSettings")
    for settings in EquipmentSettings.objects.all():
        settings.evaporation_l_min *= 60
        settings.save(update_fields=["evaporation_l_min"])


def convert_hours_to_minutes(apps, schema_editor):
    EquipmentSettings = apps.get_model("recipes", "EquipmentSettings")
    for settings in EquipmentSettings.objects.all():
        settings.evaporation_l_min /= 60
        settings.save(update_fields=["evaporation_l_min"])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_ingredient_product_id_ingredientcatalog_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsettings',
            name='evaporation_l_min',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='évaporation (L/h)'),
        ),
        migrations.RunPython(convert_minutes_to_hours, convert_hours_to_minutes),
    ]
