# Generated by Django 5.2.17 on 2026-10-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_alter_equipmentsettings_evaporation_l_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='article')),
                ('is_completed', models.BooleanField(default=False, verbose_name='acheté')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'article de la liste de courses',
                'verbose_name_plural': 'articles de la liste de courses',
                'ordering': ['is_completed', '-created_at', '-id'],
            },
        ),
    ]
