# Generated by Django 5.2.17 on 2026-10-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='actual_spent_grains_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='poids des drêches avec sac (kg)'),
        ),
        migrations.AddField(
            model_name='equipmentsettings',
            name='bag_weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='poids du sac (kg)'),
        ),
    ]
