# Generated by Django 5.2.17 on 2026-10-03 09:32

from django.db import migrations, models


def convert_kg_to_grams(apps, schema_editor):
    EquipmentSettings = apps.get_model("recipes", "EquipmentSettings")
    for settings in EquipmentSettings.objects.all():
        settings.bag_weight_kg *= 1000
        settings.save(update_fields=["bag_weight_kg"])


def convert_grams_to_kg(apps, schema_editor):
    EquipmentSettings = apps.get_model("recipes", "EquipmentSettings")
    for settings in EquipmentSettings.objects.all():
        settings.bag_weight_kg /= 1000
        settings.save(update_fields=["bag_weight_kg"])


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0031_brew_actual_spent_grains_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsettings',
            name='bag_weight_kg',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=7, verbose_name='poids du sac (g)'),
        ),
        migrations.RunPython(convert_kg_to_grams, convert_grams_to_kg),
    ]
