# Generated by Django 5.2.17 on 2026-10-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0032_alter_equipmentsettings_bag_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="addition_temperature_c",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="température d'ajout (°C)",
            ),
        ),
    ]
