# Generated by Django 5.2.17 on 2026-10-04 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0035_ingredient_for_bottling'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='recipes.ingredientcatalog', verbose_name='fiche de stock'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='received_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantité reçue'),
        ),
    ]
