# Generated by Django 5.2.17 on 2026-10-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0036_shoppingitem_catalog_shoppingitem_received_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='planned_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantité prévue'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='unité'),
        ),
    ]
