# Generated by Django 5.2.17 on 2026-10-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0037_shoppingitem_planned_quantity_shoppingitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='source_brews',
            field=models.ManyToManyField(blank=True, related_name='shopping_items', to='recipes.brew', verbose_name="brassins à l'origine"),
        ),
    ]
