# Generated by Django 5.2.17 on 2026-10-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0038_shoppingitem_source_brews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcatalog',
            name='kind',
            field=models.CharField(choices=[('malt', 'Malt'), ('hop', 'Houblon'), ('yeast', 'Levure'), ('other', 'Divers'), ('consumable', 'Consommable')], max_length=10, verbose_name='type'),
        ),
    ]
