# Generated by Django 5.2.17 on 2026-10-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0039_alter_ingredientcatalog_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de mise en bouteille'),
        ),
        migrations.AlterField(
            model_name='brew',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='date du brassage'),
        ),
    ]
