# Generated by Django 5.2.17 on 2026-10-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0040_alter_brew_completed_date_alter_brew_planned_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['is_ordered', '-created_at', '-id'], 'verbose_name': 'article de la liste de courses', 'verbose_name_plural': 'articles de la liste de courses'},
        ),
        migrations.RenameField(
            model_name='shoppingitem',
            old_name='is_completed',
            new_name='is_ordered',
        ),
        migrations.AlterField(
            model_name='shoppingitem',
            name='is_ordered',
            field=models.BooleanField(default=False, verbose_name='commandé'),
        ),
    ]
