# Generated by Django 5.2.17 on 2026-10-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0041_alter_shoppingitem_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('planned_date__isnull', True), ('completed_date__isnull', True), ('completed_date__gte', models.F('planned_date')), _connector='OR'), name='brew_bottling_after_brew'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('actual_preboil_volume_l__isnull', True), ('actual_preboil_volume_l__gte', 0), _connector='OR'), name='brew_preboil_volume_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='brew',
            constraint=models.CheckConstraint(condition=models.Q(('actual_batch_size_l__isnull', True), ('actual_batch_size_l__gte', 0), _connector='OR'), name='brew_batch_volume_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='ingredientcatalog',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_available__gte', 0)), name='catalog_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='mashstep',
            constraint=models.CheckConstraint(condition=models.Q(('temperature_c__gte', 35), ('temperature_c__lte', 100)), name='mash_temperature_between_35_100'),
        ),
        migrations.AddConstraint(
            model_name='mashstep',
            constraint=models.CheckConstraint(condition=models.Q(('duration_min__gt', 0)), name='mash_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('batch_size_l__gt', 0)), name='recipe_batch_size_positive'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('efficiency__gte', 1), ('efficiency__lte', 100)), name='recipe_efficiency_between_1_100'),
        ),
    ]
