# Generated by Django 5.2.17 on 2026-10-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0042_brew_brew_bottling_after_brew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentsettings',
            old_name='bag_weight_kg',
            new_name='bag_weight_g',
        ),
        migrations.RenameField(
            model_name='equipmentsettings',
            old_name='evaporation_l_min',
            new_name='evaporation_l_h',
        ),
    ]
