# Generated by Django 5.2.17 on 2026-10-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0043_remove_equipmentsettings_bag_weight_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='bottled_bottle_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de bouteilles à capsuler'),
        ),
        migrations.AddField(
            model_name='brew',
            name='capsule_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottling_brews', to='recipes.ingredientcatalog', verbose_name='type de capsules'),
        ),
        migrations.AddField(
            model_name='brew',
            name='capsules_consumed',
            field=models.PositiveIntegerField(default=0, verbose_name='capsules consommées'),
        ),
        migrations.AddField(
            model_name='brew',
            name='capsules_consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='capsules consommées le'),
        ),
    ]
