# Generated by Django 5.2.17 on 2026-10-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0044_brew_bottled_bottle_count_brew_capsule_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsettings',
            name='mash_efficiency',
            field=models.DecimalField(decimal_places=1, default=75, max_digits=5, verbose_name='rendement de brassage (%)'),
        ),
    ]
