# Generated by Django 5.2.17 on 2026-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0049_equipmentsettings_style_tolerance_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='target_carbonation',
            field=models.DecimalField(decimal_places=2, default=2.4, max_digits=4, verbose_name='carbonatation cible (vol. CO₂)'),
        ),
    ]
