# Generated by Django 5.2.17 on 2026-10-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0050_recipe_target_carbonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mash_temperature_grid',
            field=models.PositiveIntegerField(default=5, verbose_name='quadrillage température (°C)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_temperature_max',
            field=models.PositiveIntegerField(default=80, verbose_name='axe température maximum (°C)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_temperature_min',
            field=models.PositiveIntegerField(default=45, verbose_name='axe température minimum (°C)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_time_grid',
            field=models.PositiveIntegerField(default=15, verbose_name='quadrillage temps (min)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_time_max',
            field=models.PositiveIntegerField(default=180, verbose_name='axe temps maximum (min)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='mash_time_min',
            field=models.PositiveIntegerField(default=0, verbose_name='axe temps minimum (min)'),
        ),
    ]
