# Generated by Django 5.2.17 on 2026-10-04 20:47

from django.db import migrations, models


def update_legacy_graph_defaults(apps, schema_editor):
    Recipe = apps.get_model("recipes", "Recipe")
    Recipe.objects.filter(mash_time_max=180).update(mash_time_max=120)
    Recipe.objects.filter(mash_time_grid=15).update(mash_time_grid=5)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0051_recipe_mash_temperature_grid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='mash_time_grid',
            field=models.PositiveIntegerField(default=5, verbose_name='quadrillage temps (min)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='mash_time_max',
            field=models.PositiveIntegerField(default=120, verbose_name='axe temps maximum (min)'),
        ),
        migrations.RunPython(update_legacy_graph_defaults, migrations.RunPython.noop),
    ]
