# Generated by Django 5.2.17 on 2026-10-04 20:52

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0052_alter_recipe_mash_time_grid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mash_zones',
            field=models.JSONField(default=recipes.models.default_mash_zones, verbose_name='zones brassicoles affichées'),
        ),
    ]
