# Generated by Django 5.2.17 on 2026-10-05 13:13

from django.db import migrations, models


def mark_default_costs_as_unknown(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    Ingredient.objects.filter(cost_total=0).update(cost_total=None)


def restore_unknown_costs_to_zero(apps, schema_editor):
    Ingredient = apps.get_model("recipes", "Ingredient")
    Ingredient.objects.filter(cost_total__isnull=True).update(cost_total=0)


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0054_create_default_brewer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentsettings',
            name='cost_management_enabled',
            field=models.BooleanField(default=False, verbose_name='gestion des coûts activée'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='coût de cette quantité (€)'),
        ),
        migrations.RunPython(mark_default_costs_as_unknown, restore_unknown_costs_to_zero),
    ]
