# Generated by Django 5.2.17 on 2026-10-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0055_equipmentsettings_cost_management_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tasting_acidity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='acidité'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_alcohol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='chaleur de l’alcool'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_bitterness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='amertume perçue'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_body',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='corps'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_hops',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='arômes de houblon'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_malt',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='malté / douceur'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tasting_notes',
            field=models.TextField(blank=True, verbose_name='notes de dégustation'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tasting_malt__isnull', True), ('tasting_malt__lte', 5), _connector='OR'), models.Q(('tasting_bitterness__isnull', True), ('tasting_bitterness__lte', 5), _connector='OR'), models.Q(('tasting_hops__isnull', True), ('tasting_hops__lte', 5), _connector='OR'), models.Q(('tasting_body__isnull', True), ('tasting_body__lte', 5), _connector='OR'), models.Q(('tasting_alcohol__isnull', True), ('tasting_alcohol__lte', 5), _connector='OR'), models.Q(('tasting_acidity__isnull', True), ('tasting_acidity__lte', 5), _connector='OR')), name='recipe_tasting_scores_max_5'),
        ),
    ]
