# Generated by Django 5.2.17 on 2026-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0056_recipe_tasting_acidity_recipe_tasting_alcohol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tasting_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='note globale de dégustation'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.CheckConstraint(condition=models.Q(('tasting_rating__isnull', True), models.Q(('tasting_rating__gte', 0), ('tasting_rating__lte', 5)), _connector='OR'), name='recipe_tasting_rating_between_0_5'),
        ),
    ]
