# Generated by Django 5.2.17 on 2026-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0057_recipe_tasting_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcatalog',
            name='fermentation_temperature_max_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='température de fermentation maximale (°C)'),
        ),
        migrations.AddField(
            model_name='ingredientcatalog',
            name='fermentation_temperature_min_c',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='température de fermentation minimale (°C)'),
        ),
        migrations.AddConstraint(
            model_name='ingredientcatalog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fermentation_temperature_max_c__isnull', True), ('fermentation_temperature_min_c__isnull', True)), models.Q(('fermentation_temperature_max_c__isnull', False), ('fermentation_temperature_min_c__isnull', False), ('fermentation_temperature_min_c__lte', models.F('fermentation_temperature_max_c'))), _connector='OR'), name='catalog_yeast_fermentation_temperature_order'),
        ),
    ]
