# Generated by Django 5.2.17 on 2026-10-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0058_ingredientcatalog_fermentation_temperature_max_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('system', 'Système')], max_length=10, verbose_name='type d’événement')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('model_name', models.CharField(blank=True, max_length=80, verbose_name='type de donnée')),
                ('object_id', models.CharField(blank=True, max_length=80, verbose_name='identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date et heure')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
