# Generated by Django 5.2.17 on 2026-10-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0059_activityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcatalog',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='coût unitaire (€)'),
        ),
    ]
