# Generated by Django 5.2.17 on 2026-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0065_recipeversion_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='status',
            field=models.CharField(choices=[('planned', 'Planifié'), ('brewing', 'Brassage en cours'), ('fermenting', 'Fermentation'), ('completed', 'Terminé')], default='planned', max_length=20, verbose_name='statut'),
        ),
    ]
