# Generated by Django 5.2.17 on 2026-10-08 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0069_remove_brew_recipe_version_synced_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_tasting_scores_max_5',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='recipe_tasting_rating_between_0_5',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_acidity',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_alcohol',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_bitterness',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_body',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_hops',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_malt',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_notes',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tasting_rating',
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_acidity',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='acidité'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_alcohol',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='chaleur de l’alcool'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_bitterness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='amertume perçue'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_body',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='corps'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_hops',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='arômes de houblon'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_malt',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='malté / douceur'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_notes',
            field=models.TextField(blank=True, verbose_name='notes de dégustation'),
        ),
        migrations.AddField(
            model_name='brew',
            name='tasting_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='note globale de dégustation'),
        ),
    ]
